<a href="https://colab.research.google.com/github/RahulRajeev88/-ML-Projects/blob/master/Spam_Classification_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_csv('/content/SPAM text message 20170820 - Data.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

**Data Cleaning & Text Preprocessing**

In [ ]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
stopwords_list=[]
for word in stopwords.words('english'):
  stopwords_list.append(word)

In [ ]:
stopwords_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
from nltk.stem.porter import PorterStemmer
porter=PorterStemmer()

In [ ]:
corpus=[]
for i in range(0,len(df)):
  review=re.sub('[^a-zA-Z0-9]',' ',df['Message'][i])
  review=review.lower()
  review=review.split()
  review=[porter.stem(word) for word in review if not word in stopwords_list]
  review=' '.join(review)
  corpus.append(review)


In [ ]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

**Train Test Split**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vec=CountVectorizer(max_features=2500)

In [ ]:
X=count_vec.fit_transform(corpus).toarray()

In [ ]:
X.shape

(5572, 2500)

In [ ]:
df['Category']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object

In [ ]:
y=pd.get_dummies(df['Category'],drop_first=True)
y



spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y_train

spam
1978     1
3989     0
3935     0
4078     0
4086     1
...    ...
3772     0
5191     0
5226     0
5390     0
860      0

[4457 rows x 1 columns]

In [ ]:
y_test

spam
3245     0
944      0
1044     0
2484     0
812      0
...    ...
4264     0
2439     0
5556     0
4205     0
4293     0

[1115 rows x 1 columns]

In [ ]:
count_vec.vocabulary_

{'go': 1001,
 'point': 1701,
 'crazi': 645,
 'avail': 338,
 'bugi': 473,
 'great': 1029,
 'world': 2447,
 'la': 1282,
 'cine': 564,
 'got': 1016,
 'wat': 2382,
 'ok': 1595,
 'lar': 1290,
 'joke': 1240,
 'wif': 2418,
 'oni': 1603,
 'free': 941,
 'entri': 811,
 'wkli': 2436,
 'comp': 600,
 'win': 2422,
 'fa': 854,
 'cup': 658,
 'final': 898,
 'tkt': 2220,
 '21st': 79,
 'may': 1430,
 '2005': 76,
 'text': 2180,
 '87121': 180,
 'receiv': 1804,
 'question': 1768,
 'std': 2077,
 'txt': 2278,
 'rate': 1786,
 'appli': 296,
 'dun': 773,
 'say': 1896,
 'earli': 777,
 'alreadi': 263,
 'nah': 1529,
 'think': 2194,
 'goe': 1004,
 'usf': 2322,
 'live': 1344,
 'around': 311,
 'though': 2200,
 'freemsg': 943,
 'hey': 1091,
 'darl': 677,
 'week': 2395,
 'word': 2444,
 'back': 351,
 'like': 1333,
 'fun': 961,
 'still': 2079,
 'tb': 2156,
 'xxx': 2470,
 'send': 1924,
 '50': 129,
 'even': 826,
 'brother': 462,
 'speak': 2049,
 'treat': 2255,
 'per': 1657,
 'request': 1837,
 'mell': 1443,
 'oru': 1622,
 'mi

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
model1=GaussianNB()
model1.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [ ]:
y_pred=model1.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 1], dtype=uint8)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8556053811659193

In [ ]:
model2=MultinomialNB()
model2.fit(X_train,y_train)
y_pred=model2.predict(X_test)
y_pred


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [ ]:
accuracy_score(y_test,y_pred)*100

98.29596412556054